# -*- coding: utf-8 -*-
"""sklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCHTrPLaHPz4REgmX9jeTU-qcw2W077E




    --> Simple integration of predictative model
    # scikit-learn
    
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd

dataset = pd.read_csv('dataset.csv')
# 1. Prepare Data (X must be 2D, y is 1D)
print("raw data", dataset)
X = dataset[['Study_Hours']]
y = dataset['Test_Score']
# 2. Split (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 3. Define and Fit
model = LinearRegression()
model.fit(X_train, y_train)

# 4. Predict
predictions = model.predict(X_test)
print(f"Prediction for 5 study hours: {model.predict([[5]])[0]:.2f}")