# -*- coding: utf-8 -*-
"""panda-numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7PqdwEcMOORf-iGwLZwGTdYYsJE9Atc
"""

import pandas as pnda
import numpy as nmpy

data = pnda.read_csv("data-set.csv")

print(data) # for debugging, showing some stuff

# Data mutation and stuff

# clean the patient id
data["Patient_ID"] = data["Patient_ID"].astype(str).str.strip() # make it a string and remove white spaces i guess
data["Name"] = data["Name"].astype(str).str.strip()

# Convert to numeric, turning errors (like 'thirty') into NaN
data["Age"] = pnda.to_numeric(data["Age"], errors='coerce')

# Basta below 0 kay NaN from numpy (loc iterates to evry value?)
data.loc[data["Age"] < 0, 'Age'] = nmpy.nan

# Weight standardize
data["Weight_kg"] = pnda.to_numeric(data["Weight_kg"], errors='coerce')

# treatment group shih
data["Treatment_Group"] = data["Treatment_Group"].astype(str).str.strip().str.upper()

print(data)

data.to_csv("clean-data-set.csv", index=False)