# -*- coding: utf-8 -*-
"""data-visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HkqWzUyG4tnjhqeCeOyJBCzgpWz78BeN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Setup: Create sample data
# Simulating a dataset: Study hours vs Test Scores

data = pd.read_csv('dataset.csv')


# np.random.seed(42)
# n_samples = 100
# data = {
#     'study_hours': np.random.normal(5, 2, n_samples),
#     'test_score': np.random.normal(70, 10, n_samples) + (np.random.normal(5, 2, n_samples) * 2),
#     'category': np.random.choice(['Group A', 'Group B'], n_samples)
# }

df = pd.DataFrame(data)

# Set style
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 2. Histogram (Distribution of scores)
sns.histplot(df['Test_Score'], bins=15, kde=True, ax=axes[0, 0], color='skyblue')
axes[0, 0].set_title('Distribution of Test Scores')

# 3. Box Plot (Identify outliers in study hours)
sns.boxplot(x=df['Sleep_Hours'], ax=axes[0, 1], color='salmon')
axes[0, 1].set_title('Spread & Outliers: Study Hours')

# 4. Scatter Plot (Relationship between Study Hours and Scores)
sns.scatterplot(data=df, x='Study_Hours', y='Test_Score', hue='Major', ax=axes[1, 0])
axes[1, 0].set_title('Relationship: Study Hours vs Score')

# 5. Heatmap (Correlation Matrix)
corr = df[['Study_Hours', 'Test_Score']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', ax=axes[1, 1])
axes[1, 1].set_title('Correlation Matrix')

plt.tight_layout()
plt.show()